-- Q1. What is the total revenue generated by male vs. female customers? ( to help them design

select gender, sum(purchase_amount) as revenue
from mytable
group by gender


-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount from mytable 
where discount_applied = "YES" and purchase_amount>= (select avg(purchase_amount) from mytable)



--  Q3. Which are the top 5 products with the highest average review rating?( which item to sold at premium price

SELECT item_purchased, AVG(review_rating) AS "Average Product Rating"
FROM mytable
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, AVG(purchase_amount) as average_purchase_amount from mytable
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT 
    subscription_status,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM mytable
WHERE subscription_status IN ('Yes', 'No')
GROUP BY subscription_status
ORDER BY subscription_status;



-- Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
COUNT(*) as total_purchase,
    (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS discount_percentage
FROM mytable
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

select customer_id, previous_purchases,
CASE 
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
WHEN previous_purchases > 10 THEN 'Loyal'
ELSE 'Unknown'
END as customer_type
FROM mytable;


-- Q8. What are the top 3 most purchased products within each category?

USE customer_behaviour;
SELECT category, item_purchased, total_purchases
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rank_in_category
    FROM mytable
    GROUP BY category, item_purchased
) AS ranked
WHERE rank_in_category <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers from mytable
where previous_purchases > 5 
group by subscription_status;


-- Q10. What is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue 
from mytable
group by age_group
order by total_revenue desc
